image: gitpod/workspace-full-vnc
tasks:
  - init: |
      echo "Starting VNC setup..."
      sudo apt-get update
      sudo apt-get install -y tigervnc-tools novnc xfce4 xfce4-goodies xfce4-panel xfce4-settings xfce4-terminal
      echo -e '#!/bin/sh\nstartxfce4' > ~/.vnc/xstartup
      chmod +x ~/.vnc/xstartup
      echo "Krypton" | vncpasswd -f > ~/.vnc/passwd
      vncserver :1 -geometry 1280x720
    command: |
      /usr/share/novnc/utils/novnc_proxy --vnc localhost:5901 --listen 6080
ports:
  - port: 6080
    onOpen: open-browser
